### PR TITLE
Modernization for iOS 13 plus a bit of branding.

### PR DESCRIPTION
**Pull request by chockenberry**
This pull request contains quite a few things:

* Support for Dark Mode in iOS 13
* A workaround for the UIReferenceLibraryViewController slowness in iOS 13 (see comment in `initiateSearch()` of `AddWordViewController`)
* Some subtle new branding for the app (using color and the American Typewriter font)
* A check for text on the clipboard when the app becomes frontmost
* A partial fix for a janky animation from WordListViewController to AddWordViewController

Feel free to cherry pick whatever you want.

### CODE REVIEW

**Comment by chockenberry** [comment]
I also addressed the issues in https://github.com/willhains/Kotoba/pull/35 - there's a change in this pull request that scales the text in `textField` down to 12 pt.

**Comment by gruber** [comment]
On Nov 18, 2019, at 3:30 PM, Craig Hockenberry <notifications@github.com> wrote:

> This pull request contains quite a few things:
> 
> Support for Dark Mode in iOS 13
> A workaround for the UIReferenceLibraryViewController slowness in iOS 13
> * Some subtle new branding for the app (using color and the American Typewriter font)
> * A check for text on the clipboard when the app becomes frontmost
> A partial fix for a janky animation from WordListViewController to AddWordViewController
> Feel free to cherry pick whatever you want.
> 
> 

Chef’s kiss. Thanks for doing this, CHOCK!

It’s really so bizarrely coincidental that it happened to me *now*, but I’m going through some vision issues related to cataracts that make it very hard for me to read black-on-white text. Dark Mode has been godsend for me remaining able to work.

—J.G.

**Comment by gruber** [comment]
Built and installed. Took me 20 minutes to figure out I couldn’t sign it because Xcode had signed me out of my ADC account, but rather than tell me that, it just spun and spun and spun and spun.

American Typewriter: I generally don’t like this font ever but this might be the rare exception. I think I like it here. I leave it up to Will of course.

Colors: look good to me.

I forget where we stand on this, but Chock: I really wish that Kotoba could sync it’s history file via iCloud. I know, I know, sync is hard. But I think a simple plist that gets read on launch and written to after every search should “just work”?

Is there a “correct” location in iCloud Drive where such a file should go?

—J.G.

**Comment by willhains** [comment]
CHOCKtastic!

I have blindly merged the PR, because, well, it's CHOCK. I'm having some trouble with my iMac and Xcode today, so I'll take a closer look after I sort that out. Thanks again, @chockenberry!

@gruber Regarding sync, I think we are thinking the same thing for the solution — that's basically what we discussed over iMessage a few months ago. I just haven't gotten around to it yet. The only thing I want to check is whether it's better/safer to keep the words in separate, tiny files, rather than one large one, in case iCloud shits the bed — in which case at best it would stop syncing with no obvious way to fix, and at worst you'd lose everything.

**Comment by willhains** [comment]
@gruber Opened #42 for syncing, and added a comment to #34 regarding the proposed solution(s) above.

**Comment by chockenberry** [comment]
@gruber @willhaines The current search history is stored in the device preferences file. It should be very simple to move that over to the iCloud key/value store.

Almost did it with this update but it could be a problem if you have multiple devices with different histories. My experience with the iCloud key/value store is that it doesn’t do a very good job at merging, so it’s probably a case of “first to write wins”. And won’t be obvious without some UI.

**Comment by willhains** [comment]
@chockenberry @gruber The other problem is that this isn't (and can't be) an App Store app. So it doesn't have iCloud entitlements.

**Comment by chockenberry** [comment]
@willhains iCloud will work in an app that’s not in the App Store. It is, however, another hurdle for folks like @gruber to jump over when getting a build onto their device. Lots of knobs on the provisioning web page.

**Comment by willhains** [comment]
@chockenberry Interesting! Well then that is back on the table! I think I still like the idea of letting the user choose where their data are stored, but it would be great if "iCloud" was a choice on that list.

**Comment by chockenberry** [comment]
Took a crack at it with pull request #45.

**Pull request merged**
